# CellBin2.0 contrib, AGPL-3.0 license
# ssDNA=1, DAPI=2, HE=3, IF=4, Transcriptomics=5, Protein=6, UNKNOWN=10

trackPoints:
  detect_channel: -1 # for inputing 3-channel image, specify detection channel, defaults to convert to single channel
  first_level_thr: 5  # [th  # th2) -> track_point_score = 1
  second_level_thr: 20  # [th2  # inf) -> track_point_score = 2
  good_thresh: 5  # value above this threshold is counted as good_fov 
  process: 10  # number of inference process for point detection 
  conf_filter: 0.5  # filter detection results base on this threshold, no filtering applied for values lower than 0 # only points with score above 0.5 are kept for global template 
  high_freq_angle_thr: 0.05  # 
  DEFAULT_STAIN_TYPE: 1  # staining type ssDNA
  SUPPORTED_STAIN_TYPE: [1, 2, 3]  # staining type ssDAN, DAPI,HE
  ssDNA_weights_path: points_detect_yolov5obb_SSDNA_20220513_pytorch.onnx  # checkpoint file for ssDNA staining image
  DAPI_weights_path: points_detect_yolov5obb_SSDNA_20220513_pytorch.onnx  # checkpoint file for DAPI staining image
  HE_weights_path: points_detect_yolov5obb_SSDNA_20220513_pytorch.onnx  # checkpoint file for HE staining image
  IF_weights_path: points_detect_yolov5obb_SSDNA_20220513_pytorch.onnx  # checkpoint file for IF staining image
  GPU: 0  # GPU id used for inference
  num_threads: 0  # number of threads used for inference 

clarity:
  GPU: 0  # GPU id used for inference 
  num_threads: 0  # number of threads used for inference
#  DEFAULT_STAIN_TYPE: 1  # staining type ssDNA
#  SUPPORTED_STAIN_TYPE: [1, 2]  # staining type ssDNA, DAPI
  ssDNA_weights_path: clarity_eval_mobilev3small05064_DAPI_20230608_pytorch.onnx  # checkpoint file for ssDNA staining image
  DAPI_weights_path: clarity_eval_mobilev3small05064_DAPI_20230608_pytorch.onnx  # checkpoint file for DAPI staining image
  #  thr: 0.85
  #  cluster_area_thr: 0.05
  #  cluster_width_thr: 0.2
  #  cluster_height_thr: 0.2
  #  batch_size: 2000

trackLines:
  score_thr: 0
  topk: 10

chipDetector:
  detect_channel: -1
  score_thr: 0.1  # score threshold
  stage1_weights_path: chip_detect_11obbn_640_stage1_20250402_pytorch.onnx
  stage2_weights_path: chip_detect_yolo11x_1024_stage2_20250411_2e3_equ_pytorch.onnx
  GPU: 0
  num_threads: 0

templateReferenceV1:
  pair_points_thr: 10
  pair_points_qc_thr: 5
  range_image_size_thr: 5000
  pair_correct_thr: 20
  cluster_num_thr: 10

templateReferenceV2:
  v2_ssDNA_pass_thr: 0.1
  v2_HE_pass_thr: 0.01
  v2_scale_range_thr: [0.3, 1.7]
  v2_scale_limits: 0.5
  v2_rotate_range_thr: 35
  v2_search_range_thr: 500
  v2_rotate_fov_min_thr: 7

tissueSegmentation:
  ssDNA_weights_path: tissueseg_bcdu_S_240618_tf.onnx
  DAPI_weights_path: tissueseg_bcdu_SDI_230523_tf.onnx
  HE_weights_path: tissueseg_bcdu_H_20241018_tf.onnx
  IF_weights_path:
  Transcriptomics_weights_path: tissueseg_bcdu_rna_220909_tf.onnx
  Protein_weights_path: tissueseg_bcdu_rna_220909_tf.onnx
  GPU: 0
  num_threads: 0

cellSegmentation:
  ssDNA_weights_path: cellseg_bcdu_SHDI_221008_tf.onnx
  DAPI_weights_path: cellseg_bcdu_SHDI_221008_tf.onnx
  HE_weights_path: cellseg_bcdu_H_240823_tf.onnx
  IF_weights_path: cyto2torch_0
  Transcriptomics_weights_path: cellseg_unet_RNA_20230606.onnx
  Protein_weights_path: cellseg_unet_RNA_20230606.onnx
  GPU: 0
  num_threads: 0

Registration:
  HE_channel: 1
  rot90: true
  flip: true
  flag_pre_registration: false
  flag_chip_registration: false

cellCorrect:
  expand_r: 10
  process: 30

calibration:
  offset_thr: 20

defaultImage:
  clarity: false

geneticStandards:
  bin20_thr: -1
  bin50_thr: -1
  bin200_thr: -1


